version: '3.8'

services:

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: guilhermemorei
      MONGO_INITDB_ROOT_PASSWORD: aluno
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb

volumes:
  mongodb_data: